# Generated by Django 4.1.3 on 2022-12-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_gender_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="default/default.jpg",
                upload_to="blogs/user/%Y/%m/%d",
            ),
        ),
    ]
