# Generated by Django 4.1.3 on 2022-12-01 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_freeboard_title_noticeinform_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="freeboard", name="photo",),
        migrations.RemoveField(model_name="noticeinform", name="photo",),
        migrations.RemoveField(model_name="operateboard", name="photo",),
    ]
